# $XDG_CONFIG_HOME/k9s/views.yaml
views:
  v1/nodes:
    columns:
    - NAME
    - INTERNAL-IP
    - STATUS
    - VERSION
    - PODS
    - "%CPU"
    - "%MEM"
  # alters the pod view column layout
  v1/pods:
    sortColumn: STATUS:desc
    columns:
    - NAMESPACE
    - NAME
    - STATUS
    - READY
    - RESTARTS
    - CPU
    - MEM
    - IP
    - NODE
    - AGE
